# Generated by Django 3.0 on 2020-02-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0002_contactmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodal',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
