# Generated by Django 3.0 on 2020-02-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0003_usersmodal_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='email',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='issue',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
