# Generated by Django 3.0 on 2020-02-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0005_auto_20200222_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='issue',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='suggts',
            field=models.TextField(max_length=1000),
        ),
    ]
