# Generated by Django 3.0 on 2020-02-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0007_itemslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemslist',
            name='itemdesc',
            field=models.TextField(max_length=100),
        ),
    ]
