# Generated by Django 3.0 on 2020-02-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0008_auto_20200223_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=50)),
                ('modelname', models.CharField(max_length=50)),
                ('battery_cap', models.IntegerField()),
                ('internal_mem', models.IntegerField()),
                ('front_cam', models.IntegerField()),
                ('back_cam', models.IntegerField()),
                ('display', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('mob_pic', models.ImageField(default='Image Not Found', upload_to='Mobiles')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
