# Generated by Django 3.0 on 2020-02-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0009_mobiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiles',
            name='hearts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mobiles',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
