# Generated by Django 3.0 on 2020-03-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0010_auto_20200224_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='issue',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='suggts',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='subject',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
