# Generated by Django 3.0 on 2020-03-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0012_usersmodal_user_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=50)),
                ('modelname', models.CharField(max_length=50)),
                ('battery_cap', models.IntegerField()),
                ('internal_mem', models.CharField(max_length=20)),
                ('ram', models.IntegerField()),
                ('price', models.IntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('hearts', models.IntegerField(default=0)),
                ('display', models.CharField(max_length=25)),
                ('graphics', models.CharField(max_length=30)),
            ],
        ),
    ]
