# Generated by Django 3.0 on 2020-03-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0013_laptops'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptops',
            name='lap_pic',
            field=models.ImageField(default='Image Not Found', upload_to='Laptops'),
        ),
    ]
