# Generated by Django 3.0 on 2020-03-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0014_laptops_lap_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=50)),
                ('modelname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('is_wireless', models.BooleanField()),
                ('is_microphone_avbl', models.BooleanField()),
                ('built_matrl', models.CharField(max_length=60)),
                ('spec', models.TextField()),
            ],
        ),
    ]
