# Generated by Django 3.0 on 2020-03-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0015_headset'),
    ]

    operations = [
        migrations.AddField(
            model_name='headset',
            name='hset_pic',
            field=models.ImageField(default='Image Not Found', upload_to='HeadSet'),
        ),
    ]
