# Generated by Django 3.0 on 2020-03-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0016_headset_hset_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=50)),
                ('modelname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('cam_pic', models.ImageField(default='Image Not Found', upload_to='Cameras')),
                ('megapixel', models.IntegerField()),
                ('is_raw_mode', models.BooleanField()),
                ('battery_cap', models.IntegerField()),
                ('is_autofocus', models.BooleanField()),
                ('is_image_stable', models.BooleanField()),
            ],
        ),
    ]
