# Generated by Django 3.0 on 2020-03-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0017_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Powerbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectivity', models.CharField(choices=[('MU', 'Micro USB'), ('UB', 'USB TYPE_B'), ('UC', 'USB TYPE_C')], max_length=2)),
            ],
        ),
    ]
