# Generated by Django 3.0 on 2020-03-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0018_powerbank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerbank',
            name='connectivity',
        ),
        migrations.AddField(
            model_name='powerbank',
            name='battery_cap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='powerbank',
            name='brandname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powerbank',
            name='is_B_port',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powerbank',
            name='is_C_port',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powerbank',
            name='is_USB_port',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powerbank',
            name='modelname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powerbank',
            name='no_outputs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powerbank',
            name='pbank_pic',
            field=models.ImageField(default='Image Not Found', upload_to='Powerbank'),
        ),
        migrations.AddField(
            model_name='powerbank',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
