# Generated by Django 3.0 on 2020-03-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0020_refrigerator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kettle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=50)),
                ('modelname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('kettle_pic', models.ImageField(default='Image Not Found', upload_to='Kettle')),
                ('colour', models.CharField(max_length=15)),
                ('max_temp', models.IntegerField()),
                ('is_auto_manage', models.BooleanField()),
                ('spec', models.TextField(max_length=1000)),
                ('body_matrl', models.CharField(max_length=50)),
                ('optr_volt', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='refrig_pic',
            field=models.ImageField(default='Image Not Found', upload_to='Refrigerator'),
        ),
    ]
