# Generated by Django 3.0 on 2020-03-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0021_auto_20200317_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Television',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=50)),
                ('modelname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('tv_pic', models.ImageField(default='Image Not Found', upload_to='Television')),
                ('color', models.CharField(max_length=20)),
                ('disp_len', models.IntegerField()),
                ('spec', models.TextField()),
                ('is_smart_tv', models.BooleanField()),
            ],
        ),
    ]
