# Generated by Django 3.0 on 2020-03-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0022_television'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashingMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=50)),
                ('modelname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('wm_pic', models.ImageField(default='Image Not Found', upload_to='Television')),
                ('ltr_cap', models.IntegerField()),
                ('drum_dir', models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], max_length=10)),
                ('is_smart_wm', models.BooleanField()),
                ('is_auto_dry', models.BooleanField()),
                ('colour', models.CharField(max_length=15)),
                ('optr_volt', models.IntegerField()),
            ],
        ),
    ]
