# Generated by Django 3.0.8 on 2020-07-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0023_washingmachine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='headset',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='kettle',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='laptops',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='mobiles',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='powerbank',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='refrigerator',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='television',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='washingmachine',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
