# Generated by Django 3.0.8 on 2020-07-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0024_auto_20200717_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
