# Generated by Django 3.0.8 on 2020-07-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0025_auto_20200717_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='hearts',
            field=models.IntegerField(default=24),
        ),
    ]
