# Generated by Django 3.0.8 on 2020-07-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0026_auto_20200717_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='hearts',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='washingmachine',
            name='wm_pic',
            field=models.ImageField(default='Image Not Found', upload_to='WashingMachine'),
        ),
    ]
