# Generated by Django 3.0.8 on 2020-07-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0027_auto_20200718_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='hearts',
            field=models.IntegerField(default=23),
        ),
    ]
