# Generated by Django 3.0.8 on 2020-07-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0028_auto_20200718_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='hearts',
            field=models.IntegerField(default=17),
        ),
        migrations.AddField(
            model_name='camera',
            name='rating',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='headset',
            name='hearts',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='headset',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='kettle',
            name='hearts',
            field=models.IntegerField(default=29),
        ),
        migrations.AddField(
            model_name='kettle',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='powerbank',
            name='hearts',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='powerbank',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='hearts',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='television',
            name='hearts',
            field=models.IntegerField(default=23),
        ),
        migrations.AddField(
            model_name='television',
            name='rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='washingmachine',
            name='hearts',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='washingmachine',
            name='rating',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='hearts',
            field=models.IntegerField(default=24),
        ),
    ]
