# Generated by Django 3.0.8 on 2020-07-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0029_auto_20200718_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='camerareview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('cameraid', models.IntegerField()),
                ('reviewmsg', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='fridgereview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('fridgeid', models.IntegerField()),
                ('reviewmsg', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='headsetreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('headsetid', models.IntegerField()),
                ('reviewmsg', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='kettlereview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('kettleid', models.IntegerField()),
                ('reviewmsg', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='laptopreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('laptopid', models.IntegerField()),
                ('reviewmsg', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='mobilereview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('mobileid', models.IntegerField()),
                ('reviewmsg', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='powerbankreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('powerbankid', models.IntegerField()),
                ('reviewmsg', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='televisionreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('televisionid', models.IntegerField()),
                ('reviewmsg', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='washmanchinereview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('washmachineid', models.IntegerField()),
                ('reviewmsg', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='camera',
            name='hearts',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='camera',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='headset',
            name='hearts',
            field=models.IntegerField(default=19),
        ),
        migrations.AlterField(
            model_name='headset',
            name='rating',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='kettle',
            name='hearts',
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='kettle',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='hearts',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='powerbank',
            name='hearts',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='powerbank',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='rating',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='television',
            name='hearts',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='washingmachine',
            name='hearts',
            field=models.IntegerField(default=29),
        ),
        migrations.AlterField(
            model_name='washingmachine',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
