# Generated by Django 3.0.8 on 2020-07-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRSapp', '0032_auto_20200719_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('userid', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='camera',
            name='hearts',
            field=models.IntegerField(default=17),
        ),
        migrations.AlterField(
            model_name='camera',
            name='rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='headset',
            name='hearts',
            field=models.IntegerField(default=26),
        ),
        migrations.AlterField(
            model_name='headset',
            name='rating',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='kettle',
            name='hearts',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='kettle',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='hearts',
            field=models.IntegerField(default=19),
        ),
        migrations.AlterField(
            model_name='powerbank',
            name='hearts',
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='powerbank',
            name='rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='hearts',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='rating',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='television',
            name='hearts',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='washingmachine',
            name='hearts',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='washingmachine',
            name='rating',
            field=models.IntegerField(default=6),
        ),
    ]
